name: plsjstlogin
version: ${pluginVersion}
main: com.sobble.pleasejustlogin.bukkit.OpenLoginBukkit
description: 'Fork of OpeNLogin with more features!'
website: 'https://www.nickuc.com'
api-version: 1.13
author: Sobble6466
authors:
  - OpenLogin Contributors
  - NickUC
folia-supported: true
softdepend:
  - ProtocolLib
commands:
  changepassword:
    description: 'Changes your password'
    aliases:
      - 'changepass'
  login:
    description: 'Log in to your account'
    aliases:
      - 'log'
      - 'l'
  plsjstlogin:
    description: 'PLEASE JUST LOGIN management command'
  plsjstadmin:
    description: 'PLEASE JUST LOGIN admin tools'
  register:
    description: 'Register your account'
    aliases:
      - 'reg'
  unregister:
    description: 'Unregister your account'
    aliases:
      - 'unreg'

permissions:
  plsjstlogin.admin:
    description: 'Defines a player as admin'
    default: op
  plsjstlogin.command.changepassword:
    description: 'Allows use the command /changepassword'
    default: true
  plsjstlogin.command.login:
    description: 'Allows use the command /login'
    default: true
  plsjstlogin.command.plsjstlogin:
    description: 'Allows use the command /plsjstlogin'
    default: true
  plsjstlogin.command.plsjstadmin:
    description: 'Allows use the command /plsjstadmin'
    default: op
  plsjstlogin.command.register:
    description: 'Allows use the command /register'
    default: true
  plsjstlogin.command.unregister:
    description: 'Allows use the command /unregister'
    default: true
